# -*- coding: utf-8 -*-
"""Streamlit : build and share data apps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NKkGWstk1NASqkkHLmWCz500133QM2OS
"""

pip install streamlit

import pandas as pd
url = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
df = pd.read_csv(url)
df.head()

df.info()

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#filterer les données en fonction de la region sélectionnés
def filtrer_par_continent(continent):
 if continent =='Tous':

    return df
    return df[df['continent'] == continent]

# creer le heatmap
st.title('analyser de corrélation et de distribution')
st.sidebar.header('Filter par continent')
selected_continent = st.sidebar.selectbox("selectionner un continent", ['Tous']+df['continent'].unique().tolist())
#filter les données en foncction des données selectionner
data_filtred = filtrer_par_continent(selected_continent)

# afficher les permier lignes des données
st.write("apercu des données:")
st.write(data_filtred.head())

# analyser de correlation
st.write("matrice de corrélation")
corr_matrix = data_filtred.corr()
st.write(corr_matrix.style.background_gradient(cmap='coolwarm'))
# Distribution des colonnes numériques
st.write("Distribution des colonnes numériques:")
for col in data_filtred.select_dtypes(include=['float64', 'int64']).columns:
    st.write(f"**{col}**:")
    fig, ax = plt.subplots()
    sns.histplot(data_filtred[col], kde=True, ax=ax)
    st.pyplot(fig)

# Affichage des boutons de filtrage par continent
st.write("Boutons de filtrage par continent:")
continents = ['Tous'] + df['continent'].unique().tolist()
for continent in continents:
    button_clicked = st.button(continent)
    if button_clicked:
        selected_continent = continent
        data_filtered = filtrer_par_continent(selected_continent)

# Affichage du footer
st.markdown(
    """
    **Conseil :** Explorez les différentes options dans la barre latérale pour visualiser les résultats.
    """)